name: cloudflare_dns
description: "Aplicativo Android em Flutter para gerenciamento de registros DNS via Cloudflare API."
publish_to: 'none'
version: 1.0.3

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  shared_preferences: ^2.2.3
  local_auth: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_size: 21

flutter:
  uses-material-design: true
